language: go
dist: bionic
go:
  - 1.13.x
  - 1.14.x
  - tip

before_install:
  - sudo apt-get install -y pkg-config libczmq4 libczmq-dev libsodium-dev

script:
  - make test
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)